# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-ws-notify

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true
  # The tag format to use (e.g. v1.0.0)
  version_tag_format: "v{{version}}"
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  # allow bumping the major release via label
  major_bump_labels:
    - "Expeditor: Bump Version Major"

release_branches:
  - main:
      version_constraint: 1.*

artifact_channels:
  - unstable
  - chef-dke-lts2024

changelog:
  rollup_header: Changes not yet released to rubygems.org

pipelines:
  - verify:
      description: Pull Request validation tests
      public: true
  - habitat/build:
      env:
        - HAB_NONINTERACTIVE: "true"
        - HAB_NOCOLORING: "true"
        - HAB_STUDIO_SECRET_HAB_NONINTERACTIVE: "true"
        - HAB_BLDR_CHANNEL: "LTS-2024"
        - HAB_REFRESH_CHANNEL: "LTS-2024"
  - habitat/test:
      description: Execute tests against the habitat artifact
      definition: .expeditor/habitat-test.pipeline.yml
      env:
        - HAB_NONINTERACTIVE: "true"
        - HAB_NOCOLORING: "true"
        - HAB_STUDIO_SECRET_HAB_NONINTERACTIVE: "true"
      trigger: pull_request

subscriptions:
  # These actions are taken, in order they are specified, anytime a Pull Request is merged.
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Expeditor: Skip Version Bump"
            - "Expeditor: Skip All"
      - bash:.expeditor/update_version.sh:
          only_if: built_in:bump_version
      - built_in:update_changelog:
          ignore_labels:
            - "Expeditor: Skip Changelog"
            - "Expeditor: Skip All"
      - trigger_pipeline:habitat/build:
          only_if: built_in:bump_version
          ignore_labels:
            - "Expeditor: Skip Habitat"
            - "Expeditor: Skip All"

  # Subscribe to the promotion of the unstable channel to stable(chef-dke-lts2024)
  - workload: project_promoted:{{agent_id}}:unstable:*
    actions:
      - built_in:promote_habitat_packages
