---
on:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: integration-${{ github.ref }}
  cancel-in-progress: true

env:
  CHEF_TEST_KITCHEN_ENTERPRISE: true

jobs:
  dokken:
    env:
      KITCHEN_LOCAL_YAML: kitchen.dokken.yml
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup Machine
        run: |
          bundle config set --local with 'integration'
          bundle install
      - name: Verify Dokken
        run: bundle exec kitchen verify

  vagrant:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - name: Install Vagrant VirtualBox
        run: sudo apt-get update && sudo apt-get install -y virtualbox vagrant
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup Machine
        run: |
          bundle config set --local with 'integration'
          bundle install
      - name: Verify Vagrant
        run: bundle exec kitchen verify almalinux-9

  macos:
    env:
      KITCHEN_LOCAL_YAML: kitchen.exec.yml
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup Machine
        run: |
          bundle config set --local with 'integration'
          bundle install
      - name: Verify macOS
        run: bundle exec kitchen verify macos-latest

  windows:
    env:
      KITCHEN_LOCAL_YAML: kitchen.exec.yml
    runs-on: windows-latest
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup Machine
        run: |
          bundle config set --local with 'integration'
          bundle install
      - name: Verify Windows
        run: bundle exec kitchen verify windows-latest

  linux:
    env:
      KITCHEN_LOCAL_YAML: kitchen.exec.yml
    runs-on: ubuntu-latest
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup Machine
        run: |
          bundle config set --local with 'integration'
          bundle install
      - name: Verify Linux
        run: bundle exec kitchen verify ubuntu-latest
