---
on:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: integration-${{ github.ref }}
  cancel-in-progress: true

env:
  CHEF_TEST_KITCHEN_ENTERPRISE: true
  machine_user: test_user
  machine_pass: Pass@word1
  SPEC_OPTS: --format progress

jobs:
  dokken:
    env:
      KITCHEN_LOCAL_YAML: kitchen.dokken.yml
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup Machine
        run: |
          bundle config set --local with 'integration'
          bundle install
      - name: Verify Dokken
        run: bundle exec kitchen verify

  vagrant:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - name: Install VirtualBox
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common libarchive-tools virtualbox
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install Vagrant
        run: |
          bundle config set --local with 'integration'
          bundle install --binstubs
          export PATH="$(pwd)/bin:$PATH"
          vagrant -v
      - name: Verify Vagrant
        run: |
          export PATH="$(pwd)/bin:$PATH"
          bundle exec kitchen verify almalinux-9

  macos:
    env:
      machine_port: 22
      KITCHEN_LOCAL_YAML: kitchen.proxy.yml
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup Machine
        run: |
          sudo dscl . -create /Users/${{ env.machine_user }}
          sudo dscl . -create /Users/${{ env.machine_user }} UserShell /bin/bash
          sudo dscl . -create /Users/${{ env.machine_user }} RealName "${{ env.machine_user }}"
          sudo dscl . -create /Users/${{ env.machine_user }} UniqueID 1001
          sudo dscl . -create /Users/${{ env.machine_user }} PrimaryGroupID 80
          sudo dscl . -create /Users/${{ env.machine_user }} NFSHomeDirectory /Users/${{ env.machine_user }}
          sudo dscl . -passwd /Users/${{ env.machine_user }} ${{ env.machine_pass }}
          sudo createhomedir -c -u ${{ env.machine_user }}
          echo "${{ env.machine_user }} ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
          bundle config set --local with 'integration'
          bundle install
      - name: Verify macOS
        run: bundle exec kitchen verify localhost

  windows:
    env:
      machine_port: 5985
      KITCHEN_LOCAL_YAML: kitchen.proxy.yml
    runs-on: windows-latest
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup Machine
        run: |
          winrm.cmd quickconfig -q
          net user /add ${{ env.machine_user }} ${{ env.machine_pass }}
          net localgroup administrators ${{ env.machine_user }} /add
          bundle config set --local with 'integration'
          bundle install
      - name: Verify Windows
        run: bundle exec kitchen verify windows

  linux:
    env:
      machine_port: 22
      KITCHEN_LOCAL_YAML: kitchen.proxy.yml
    runs-on: ubuntu-latest
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup Machine
        run: |
          sudo useradd -m ${{ env.machine_user }}
          echo "${{ env.machine_user }}:${{ env.machine_pass }}" | sudo chpasswd
          echo "${{ env.machine_user }} ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
          bundle config set --local with 'integration'
          bundle install
      - name: Verify Linux
        run: bundle exec kitchen verify localhost
