---
name: integration

"on":
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: integration-${{ github.ref }}
  cancel-in-progress: true

env:
  machine_user: test_user
  machine_pass: Pass@word1
  machine_port: 5985
  SPEC_OPTS: --format progress
jobs:
  integration-linux:
    name: Linux Dokken Integration Tests
    env:
      KITCHEN_LOCAL_YAML: kitchen.dokken.yml
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec kitchen test

  # FIXME: Commented out until we fix the pipelines for the RC2 release
#   integration-macos:
#     name: MacOS Integration Tests
#     runs-on: macos-13
#     strategy:
#       fail-fast: false
#       matrix:
#         ruby: ["3.3"]
#     steps:
#       - name: Install Vagrant VirtualBox
#         run: brew install --cask virtualbox vagrant
#       - uses: actions/checkout@v4
#       - uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: ${{ matrix.ruby }}
#           bundler-cache: true
#       - name: Kitchen Test
#         run: |
#           export LOGNAME=$USER
#           bundle exec kitchen test almalinux-9

  integration-windows:
    name: Windows Integration Tests
    env:
      BUNDLE_without: integration
      KITCHEN_LOCAL_YAML: kitchen.exec.yml
    runs-on: windows-latest
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
#       - name: Setup Machine
#         run: |
#           winrm.cmd quickconfig -q
#           net user /add ${{ env.machine_user }} ${{ env.machine_pass }}
#           net localgroup administrators ${{ env.machine_user }} /add
#           bundle config set --local with 'integration'
#           bundle install
      - name: Verify Windows
        run: bundle exec kitchen verify windows-latest

  integration-macos:
    env:
      KITCHEN_LOCAL_YAML: kitchen.exec.yml
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
#       - name: Setup Machine
#         run: |
#           sudo dscl . -create /Users/${{ env.machine_user }}
#           sudo dscl . -create /Users/${{ env.machine_user }} UserShell /bin/bash
#           sudo dscl . -create /Users/${{ env.machine_user }} RealName "${{ env.machine_user }}"
#           sudo dscl . -create /Users/${{ env.machine_user }} UniqueID 1001
#           sudo dscl . -create /Users/${{ env.machine_user }} PrimaryGroupID 80
#           sudo dscl . -create /Users/${{ env.machine_user }} NFSHomeDirectory /Users/${{ env.machine_user }}
#           sudo dscl . -passwd /Users/${{ env.machine_user }} ${{ env.machine_pass }}
#           sudo createhomedir -c -u ${{ env.machine_user }}
#           echo "${{ env.machine_user }} ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
#           bundle config set --local with 'integration'
#           bundle install
      - name: Verify macOS
        run: bundle exec kitchen verify macos-latest

  linux:
    env:
      KITCHEN_LOCAL_YAML: kitchen.exec.yml
    runs-on: ubuntu-latest
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
#       - name: Setup Machine
#         run: |
#           sudo useradd -m ${{ env.machine_user }}
#           echo "${{ env.machine_user }}:${{ env.machine_pass }}" | sudo chpasswd
#           echo "${{ env.machine_user }} ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
#           bundle config set --local with 'integration'
#           bundle install
      - name: Verify Linux
        run: bundle exec kitchen verify ubuntu-latest
