---
"on":
  workflow_call:

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cookstyle:
    env:
      BUNDLE_WITH: ${{ inputs.bundle_with }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.4"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Check for Gemfile
        id: check
        run: |
          if [ -f Gemfile ]; then
           echo "gemfile=true" >> $GITHUB_OUTPUT
          else
            echo "gemfile=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup Ruby
        if: steps.check.outputs.gemfile == 'true'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: r7kamura/rubocop-problem-matchers-action@v1
        if: steps.check.outputs.gemfile == 'true'
      - name: Cook Style
        if: steps.check.outputs.gemfile == 'true'
        run: bundle exec cookstyle --chefstyle

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run yaml Lint
        uses: actionshub/yamllint@main

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: |
            *.md
            !CHANGELOG.md

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.17
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          check-modified-files-only: "yes"
          base-branch: "main"

  test:
    name: Unit Test with Ruby
    runs-on: ubuntu-latest
    needs: [yamllint, cookstyle]
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.4"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Check for Gemfile
        id: check
        run: |
          if [ -f Gemfile ]; then
           echo "gemfile=true" >> $GITHUB_OUTPUT
          else
            echo "gemfile=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup Ruby
        if: steps.check.outputs.gemfile == 'true'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Rake Test
        if: steps.check.outputs.gemfile == 'true'
        run: bundle exec rake test
